--
VUHDO_DEBUFF_TYPE_NONE = 0;
VUHDO_DEBUFF_TYPE_POISON = 1;
VUHDO_DEBUFF_TYPE_DISEASE = 2;
VUHDO_DEBUFF_TYPE_MAGIC = 3;
VUHDO_DEBUFF_TYPE_CURSE = 4;
VUHDO_DEBUFF_TYPE_CHARMED = 5;



VUHDO_DEBUFF_TYPES = {
  ["Magic"] = VUHDO_DEBUFF_TYPE_MAGIC,
  ["Disease"] = VUHDO_DEBUFF_TYPE_DISEASE,
  ["Poison"] = VUHDO_DEBUFF_TYPE_POISON,
  ["Curse"] = VUHDO_DEBUFF_TYPE_CURSE
};



--
VUHDO_DEBUFF_ABILITIES = {
	["WARRIOR"] = {
	},
	["ROGUE"] = {
	},
	["HUNTER"] = {
	},
	["MAGE"] = {
		[VUHDO_DEBUFF_TYPE_CURSE] = "Geringen Fluch aufheben",
	},
	["DRUID"] = {
		[VUHDO_DEBUFF_TYPE_POISON] = "Vergiftung aufheben",
		[VUHDO_DEBUFF_TYPE_CURSE] = "Fluch aufheben",
	},
	["PALADIN"] = {
		[VUHDO_DEBUFF_TYPE_POISON] = "Reinigung des Glaubens",
		[VUHDO_DEBUFF_TYPE_DISEASE] = "Reinigung des Glaubens",
		[VUHDO_DEBUFF_TYPE_MAGIC] = "Reinigung des Glaubens",
	},
	["PRIEST"] = {
		[VUHDO_DEBUFF_TYPE_DISEASE] = "Krankheit aufheben",
		[VUHDO_DEBUFF_TYPE_MAGIC] = "Magiebannung",
	},
	["SHAMAN"] = {
		[VUHDO_DEBUFF_TYPE_POISON] = "Vergiftung heilen",
		[VUHDO_DEBUFF_TYPE_DISEASE] = "Krankheit heilen",
	},
	["WARLOCK"] = {
		[VUHDO_DEBUFF_TYPE_MAGIC] = "",
	},
	["DEATH KNIGHT"] = {
	},
};



VUHDO_IGNORE_DEBUFFS_BY_CLASS = {
	["WARRIOR"] = {
		[VUHDO_I18N_DEBUFF_ANCIENT_HYSTERIA] = true,
    [VUHDO_I18N_DEBUFF_IGNITE_MANA] = true,
    [VUHDO_I18N_DEBUFF_TAINTED_MIND] = true,
    [VUHDO_I18N_DEBUFF_VIPER_STING] = true,
    [VUHDO_I18N_DEBUFF_IMPOTENCE] = true,
    [VUHDO_I18N_DEBUFF_DECAYED_INT] = true,
    [VUHDO_I18N_DEBUFF_UNSTABLE_AFFL] = true,
  },
  ["ROGUE"] = {
    [VUHDO_I18N_DEBUFF_SILENCE] = true,
    [VUHDO_I18N_DEBUFF_ANCIENT_HYSTERIA] = true,
    [VUHDO_I18N_DEBUFF_IGNITE_MANA] = true,
    [VUHDO_I18N_DEBUFF_TAINTED_MIND] = true,
    [VUHDO_I18N_DEBUFF_VIPER_STING] = true,
    [VUHDO_I18N_DEBUFF_IMPOTENCE] = true,
    [VUHDO_I18N_DEBUFF_DECAYED_INT] = true,
    [VUHDO_I18N_DEBUFF_UNSTABLE_AFFL] = true,
  },
  ["HUNTER"] = {
    [VUHDO_I18N_DEBUFF_MAGMA_SHACKLES] = true,
    [VUHDO_I18N_DEBUFF_UNSTABLE_AFFL] = true,
  },
  ["MAGE"] = {
  	[VUHDO_I18N_DEBUFF_MAGMA_SHACKLES] = true,
    [VUHDO_I18N_DEBUFF_DECAYED_STR] = true,
    [VUHDO_I18N_DEBUFF_CRIPPLE] = true,
    [VUHDO_I18N_DEBUFF_UNSTABLE_AFFL] = true,
  },
  ["DRUID"] = {
  	[VUHDO_I18N_DEBUFF_UNSTABLE_AFFL] = true,
  },
  ["PALADIN"] = {
    [VUHDO_I18N_DEBUFF_UNSTABLE_AFFL] = true,
  },
  ["PRIEST"] = {
  	[VUHDO_I18N_DEBUFF_DECAYED_STR] = true,
    [VUHDO_I18N_DEBUFF_CRIPPLE] = true,
    [VUHDO_I18N_DEBUFF_UNSTABLE_AFFL] = true,
  },
  ["SHAMAN"] = {
    [VUHDO_I18N_DEBUFF_UNSTABLE_AFFL] = true,
  },
  ["WARLOCK"] = {
  	[VUHDO_I18N_DEBUFF_DECAYED_STR] = true,
    [VUHDO_I18N_DEBUFF_CRIPPLE] = true,
    [VUHDO_I18N_DEBUFF_UNSTABLE_AFFL] = true,
  },
  ["DEATH KNIGHT"] = {
  },
};



VUHDO_IGNORE_DEBUFFS_MOVEMENT = {
	[VUHDO_I18N_DEBUFF_FROSTBOLT] = true,
	[VUHDO_I18N_DEBUFF_MAGMA_SHACKLES] = true,
	[VUHDO_I18N_DEBUFF_SLOW] = true,
	[VUHDO_I18N_DEBUFF_CHILLED] = true,
	[VUHDO_I18N_DEBUFF_CONEOFCOLD] = true,
	[VUHDO_I18N_DEBUFF_CONCUSSIVESHOT] = true,
	[VUHDO_I18N_DEBUFF_THUNDERCLAP] = true,
	[VUHDO_I18N_DEBUFF_HOWLINGSCREECH] = true,
	[VUHDO_I18N_DEBUFF_DAZED] = true,
	[VUHDO_I18N_DEBUFF_FROST_SHOCK] = true,
};



VUHDO_IGNORE_DEBUFFS_DURATION = {
	[VUHDO_I18N_DEBUFF_PSYCHIC_HORROR] = true,
  [VUHDO_I18N_DEBUFF_CHILLED] = true,
  [VUHDO_I18N_DEBUFF_CONEOFCOLD] = true,
  [VUHDO_I18N_DEBUFF_CONCUSSIVESHOT] = true,
  [VUHDO_I18N_DEBUFF_FALTER] = true,
};



VUHDO_IGNORE_DEBUFFS_NO_HARM = {
  [VUHDO_I18N_DEBUFF_HUNTERS_MARK] = true,
  [VUHDO_I18N_DEBUFF_ARCANE_BLAST] = true,
  [VUHDO_I18N_DEBUFF_MAJOR_DREAMLESS] = true,
  [VUHDO_I18N_DEBUFF_GREATER_DREAMLESS] = true,
  [VUHDO_I18N_DEBUFF_DREAMLESS_SLEEP] = true,

  [VUHDO_I18N_DEBUFF_DELUSIONS_OF_JINDO] = true,
  [VUHDO_I18N_DEBUFF_MIND_VISION] = true,
  [VUHDO_I18N_DEBUFF_MUTATING_INJECTION] = true,
  [VUHDO_I18N_DEBUFF_BANISH] = true,
  [VUHDO_I18N_DEBUFF_PHASE_SHIFT] = true
};
